version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: yuriigouveia/reverseproxy 
  backend_user:
    build:
      context: ../udacity-c2-restapi-user
    image: yuriigouveia/user
  backend_feed:
    build:
      context: ../udacity-c2-restapi-feed  
    image: yuriigouveia/feed
  frontend:
    build:
      context: ../udacity-c2-frontend  
    image: yuriigouveia/udagram-frontend