apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8081"
    port: 8081
    targetPort: 8081
  selector:
    service: backend-feed