apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  replicas: 2
  template:
    metadata:
      labels:
        service: reverseproxy
    spec:
      containers:
      - image: yuriigouveia/reverseproxy
        name: reverseproxy
        # command: ["/bin/sh"] # initialize command
        # args: ["-c", "while true; do date >> /var/log/app.txt; sleep 5;done"] # command that forbid a pod to shutdown
        imagePullPolicy: Always          
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "1024Mi"
            cpu: "500m"       
        ports:
        - containerPort: 8081
      restartPolicy: Always